# Generated by Django 3.2 on 2021-05-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=150)),
                ('from_currency_name', models.CharField(max_length=150)),
                ('to_currency', models.CharField(max_length=150)),
                ('to_currency_name', models.CharField(max_length=150)),
                ('exchange_rate', models.CharField(max_length=150)),
                ('last_refreshed', models.DateTimeField()),
            ],
        ),
    ]
